import React, { useState, useEffect } from 'react';
import { useApp } from '../context/AppContext';
import AdminLayout from '../components/layout/AdminLayout';
import { History, Search, Download, Eye, Calendar, User, Store, ExternalLink, X, RefreshCw } from 'lucide-react';

export default function PosterHistoryPage() {
  const { generatedPosters, fetchGeneratedPosters } = useApp();
  const [searchTerm, setSearchTerm] = useState('');
  const [previewPoster, setPreviewPoster] = useState(null);

  useEffect(() => {
    fetchGeneratedPosters();
  }, [fetchGeneratedPosters]);

  const filtered = generatedPosters.filter(p => 
    (p.templateTitle || '').toLowerCase().includes(searchTerm.toLowerCase()) ||
    (p.customerName || '').toLowerCase().includes(searchTerm.toLowerCase()) ||
    (p.generatedBy || '').toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <AdminLayout>
      <div className="space-y-8">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <h1 className="text-2xl font-black font-heading text-[#0A0A0A]">Poster Generation History Log</h1>
            <p className="text-xs text-[#555555] font-medium mt-1">
              Audit all personalized posters created by shop owners through dynamic share links (Live MongoDB Atlas Database).
            </p>
          </div>

          <button
            onClick={() => fetchGeneratedPosters()}
            className="px-4 py-2.5 bg-[#FFFFFF] hover:bg-[#F5F5F3] text-[#555555] rounded-xl border border-[#E5E5E5] transition-colors flex items-center gap-2 text-xs font-bold shrink-0 self-start sm:self-auto"
            title="Refresh Poster History Logs"
          >
            <RefreshCw className="w-4 h-4" />
            <span>Refresh Logs</span>
          </button>
        </div>

        {/* Search Bar Header */}
        <div className="bg-[#FFFFFF] border border-[#E5E5E5] rounded-3xl p-6 flex flex-col sm:flex-row items-center justify-between gap-4 shadow-xs">
          <div className="relative max-w-md w-full">
            <Search className="w-4 h-4 text-[#777777] absolute left-3.5 top-3" />
            <input
              type="text"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              placeholder="Search by customer name, template title, or shop owner..."
              className="w-full bg-[#F8F8F6] border border-[#E5E5E5] focus:border-[#C1121F] text-[#111111] placeholder-[#777777] pl-10 pr-4 py-2 rounded-xl text-xs outline-none"
            />
          </div>
          <span className="text-xs text-[#555555] font-medium shrink-0">
            Total Records in Database: <strong className="text-[#0A0A0A] font-bold">{filtered.length}</strong>
          </span>
        </div>

        {/* TABLE LOG */}
        {filtered.length === 0 ? (
          <div className="bg-[#FFFFFF] border border-[#E5E5E5] rounded-3xl p-12 text-center text-[#555555] space-y-2">
            <History className="w-12 h-12 text-[#C1121F] mx-auto mb-2 opacity-40" />
            <h3 className="font-heading font-bold text-base text-[#0A0A0A]">No Generated Poster Records Found</h3>
            <p className="text-xs text-[#777777]">
              {searchTerm ? 'No poster records match your search criteria.' : 'No customer poster generations recorded in MongoDB Atlas yet. Share a template link and generate a poster to populate history.'}
            </p>
          </div>
        ) : (
          <div className="bg-[#FFFFFF] border border-[#E5E5E5] rounded-3xl overflow-hidden shadow-xs">
            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse">
                <thead>
                  <tr className="bg-[#F5F5F3] border-b border-[#E5E5E5] text-[11px] font-bold text-[#111111] uppercase tracking-wider">
                    <th className="py-4 px-6">Poster Preview</th>
                    <th className="py-4 px-6">Customer / Student</th>
                    <th className="py-4 px-6">Template Used</th>
                    <th className="py-4 px-6">Generated By (Shop Owner)</th>
                    <th className="py-4 px-6">Date & Time</th>
                    <th className="py-4 px-6 text-right">Action</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-[#E5E5E5] text-xs">
                  {filtered.map((item) => (
                    <tr key={item.id || item._id} className="hover:bg-[#FFF1F2] transition-colors">
                      <td className="py-3 px-6">
                        <div className="w-12 h-14 bg-[#0A0A0A] rounded-lg overflow-hidden border border-[#E5E5E5] flex items-center justify-center">
                          {item.previewUrl ? (
                            <img src={item.previewUrl} alt="Poster" className="w-full h-full object-cover" />
                          ) : (
                            <History className="w-5 h-5 text-slate-500" />
                          )}
                        </div>
                      </td>
                      <td className="py-3 px-6 font-bold text-[#0A0A0A]">
                        {item.customerName || 'Customer'}
                      </td>
                      <td className="py-3 px-6 text-[#555555] font-medium">
                        {item.templateTitle || 'Custom Template'}
                      </td>
                      <td className="py-3 px-6 text-[#C1121F] font-bold">
                        {item.generatedBy || 'Shop Owner'}
                      </td>
                      <td className="py-3 px-6 text-[#777777]">
                        {item.date || (item.createdAt ? new Date(item.createdAt).toLocaleDateString() : 'Just now')}
                      </td>
                      <td className="py-3 px-6 text-right">
                        <button
                          onClick={() => setPreviewPoster(item)}
                          className="px-3 py-1.5 bg-[#FFF1F2] hover:bg-red-100 text-[#C1121F] font-bold rounded-xl text-xs inline-flex items-center gap-1 border border-red-200 transition-colors"
                        >
                          <Eye className="w-3.5 h-3.5" />
                          Inspect
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {/* PREVIEW MODAL */}
        {previewPoster && (
          <div className="fixed inset-0 z-50 bg-[#0A0A0A]/80 backdrop-blur-sm flex items-center justify-center p-4">
            <div className="bg-[#FFFFFF] border border-[#E5E5E5] rounded-3xl max-w-lg w-full p-6 shadow-2xl space-y-4 text-[#111111]">
              <div className="flex items-center justify-between">
                <h3 className="font-heading font-bold text-lg text-[#0A0A0A]">Poster Generation Audit Details</h3>
                <button onClick={() => setPreviewPoster(null)} className="p-1 text-[#555555] hover:text-[#0A0A0A]">
                  <X className="w-5 h-5" />
                </button>
              </div>

              {previewPoster.previewUrl && (
                <div className="bg-[#F8F8F6] p-4 rounded-2xl border border-[#E5E5E5] flex justify-center">
                  <img src={previewPoster.previewUrl} alt="Poster" className="max-h-80 object-contain rounded-lg shadow-sm" />
                </div>
              )}
              <div className="text-xs space-y-2 text-[#555555] font-medium bg-[#F8F8F6] p-4 rounded-2xl border border-[#E5E5E5]">
                <p><strong className="text-[#0A0A0A]">Customer Name:</strong> {previewPoster.customerName}</p>
                <p><strong className="text-[#0A0A0A]">Generated By:</strong> {previewPoster.generatedBy}</p>
                <p><strong className="text-[#0A0A0A]">Template:</strong> {previewPoster.templateTitle}</p>
                <p><strong className="text-[#0A0A0A]">Timestamp:</strong> {previewPoster.date || previewPoster.createdAt}</p>
              </div>
              <div className="flex justify-end pt-2">
                <button
                  onClick={() => setPreviewPoster(null)}
                  className="px-4 py-2 bg-[#F5F5F3] hover:bg-[#E5E5E5] text-[#555555] font-bold text-xs rounded-xl border border-[#E5E5E5]"
                >
                  Close
                </button>
              </div>
            </div>
          </div>
        )}
      </div>
    </AdminLayout>
  );
}
